config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'clients/new'

  resources :teams, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :specialofficers, only: [:index, :show]
  match 'contact', to: 'contact#new', via: :get
  match 'contact', to: 'contact#create', via: :post

  root 'home#index'
  get 'admin/' => 'admin/administrations#index'
  namespace :admin do
    resources :administrations
    resources :teams
    resources :events
  end
  get 'haircut' => 'home#haircut'
  get 'haircolor' => 'home#haircolor'
  get 'hairtreatment' => 'home#hairtreatment'
  get 'hairrituals' => 'home#hairrituals'
  get 'aboutus' => 'home#aboutus'
  get 'gallery' => 'home#gallery'
  get 'products' => 'home#products'

  get 'specialoffers' => 'home#specialoffers'

end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :small_image, EventSmallImageUploader
  mount_uploader :image, EventImageUploader
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/administrations_controller.rb
class Admin::AdministrationsController < AdminsController
  def index

  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminsController
  def index
    @events = Event.all
  end

  def show
    find_event
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_events_path
      flash[:notice] = "Event Created"
    else
      render :new
      flash[:notice] = "Event not created, please try again."
    end
  end

  def edit
    find_event
  end

  def update
    find_event
    @event.update_attributes(event_params)
    redirect_to admin_events_path
    flash[:notice] = "Event updated"
  end

  def destroy
    find_event
    @event.destroy
    redirect_to admin_events_path
    flash[:notice] = "Event Deleted"
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit!
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < AdminsController
  def index
    @members = Team.all
  end

  def show
    find_team_member
  end

  def edit
    find_team_member
  end

  def update
    find_team_member
    @member.update_attributes(member_params)
    redirect_to admin_teams_path
    flash[:notice] = "Team member updated"
  end

  def new
    @member = Team.new
  end

  def create
    @member = Team.new(member_params)
    if @member.save
      redirect_to admin_teams_path
      flash[:notice] = "Team member created"
    end
  end

  def destroy
    find_team_member
    @member.destroy
    redirecto_to admin_teams_path
    flash[:notice] = "Team member deleted"
  end

  private

  def member_params
    params.require(:team).permit!
  end

  def find_team_member
    @member = Team.find(params[:id])
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :admin_check
  layout "admin/administrations"
  def admin_check
    if current_user.present? && current_user.is_admin?
    else
      redirect_to root_path
      flash[:notice] = "You are not an administrator."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
def new
    @message = Message.new
end

  def create
      @message = Message.new(contact_params)
      UserMailer.welcome_email(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
  end

end

def contact_params
    params.require(:message).permit!
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def haircut
    
  end

  def haircolor
    
  end

  def hairtreatment
    
  end

  def hairrituals
    
  end

  def aboutus
    
  end

  def gallery
    
  end

  def products
    
  end

  def specialoffers
     @message = Message.new
  end

  def events
    
  end

  def contactus
    
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @member = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/admin/administrations/index.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tricho
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    = javascript_include_tag 'application'
  %body.admin-area
    - if flash[:notice]
      .flash-notice
        = flash[:notice]
    .logo-area
      = link_to(image_tag("tricho-salon-wellington.png"), root_path)
    = yield

app/views/admin/events/_form.html.haml
.table_wrapper.new_team
  - if @event.image.present?
    = image_tag ("#{@event.image}")
  %ul
    = form_for [:admin, @event] do |f|
      %li
        = f.label :title
        %br/
        = f.text_field :title
      %li
        = f.label :image
        %br/
        = f.file_field :image
      %li
        = f.label :description
        %br/
        = f.text_area :description, rows: "40"
      = f.submit class: "btn btn-primary"
  %p
    = link_to "Destroy", @event, method: "delete"

app/views/admin/events/edit.html.haml
= render 'form'

app/views/admin/events/index.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    Our Team
  %p.color-white.intro.shadow View a list of our stylists
.table_wrapper_team.new_team
  %ul
    - @events.each do |team|
      %li
        - if team.image.present?
          = link_to(image_tag("#{team.image}"), team )
        %br/
        %span.team_name= team.title
        %br/
        %span.team_job= markdown(team.description)
        %br/
        %span.team_link
          = link_to "Edit",  edit_admin_event_path(team)

app/views/admin/events/new.html.haml
= render 'form'

app/views/admin/teams/_form.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    Team Member
  %p.color-white.intro.shadow Team Member Options
.table_wrapper.new_team
  - if @member.image.present?
    = image_tag ("#{@member.image}")
  %ul
    = form_for [:admin, @member] do |f|
      %li
        = f.label :name
        %br/
        = f.text_field :name
      %li
        = f.label :job
        %br/
        = f.text_field :job
      %li
        = f.label :image
        %br/
        = f.file_field :image
      %li
        = f.label :bio
        %br/
        = f.text_area :bio, rows: "40"
      = f.submit "Create Tem Member", class: "btn btn-primary"
  %p
    = link_to "Remove Team Member", @member, method: "delete"

app/views/admin/teams/edit.html.haml
= render "form"

app/views/admin/teams/index.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    Our Team
  %p.color-white.intro.shadow View a list of our stylists
.table_wrapper_team.new_team
  %ul
    - @members.each do |team|
      %li.float-left
        = link_to(image_tag("#{team.image}"), team )
        %br/
        %span.team_name= team.name
        %br/
        %span.team_job= team.job
        %br/
        %span.team_link
          = link_to "Edit",  edit_admin_team_path(team)

app/views/admin/teams/new.html.haml
= render 'form'

app/views/contact/new.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    News &amp; Events
= render partial: "home/email_form", locals: {area: "Contact Us"}
:javascript
  $( document ).ready(function() {
      $.supersized({  
    // Functionality
    slideshow               :   0,      // Slideshow on/off
    autoplay        : 1,      // Slideshow starts playing automatically
    start_slide             :   1,      // Start slide (0 is random)
    stop_loop       : 0,      // Pauses slideshow on last slide
    random          :   0,      // Randomize slide order (Ignores start slide)
    slide_interval          :   5000,   // Length between transitions
    transition              :   1,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
    transition_speed    : 2000,   // Speed of transition
    new_window        : 1,      // Image links open in new window/tab
    pause_hover             :   0,      // Pause slideshow on hover
    keyboard_nav            :   0,      // Keyboard navigation on/off
    performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
    image_protect     : 1,      // Disables image dragging and right click with Javascript
               
    // Size & Position               
    min_width           :   0,      // Min width allowed (in pixels)
    min_height            :   0,      // Min height allowed (in pixels)
    vertical_center         :   1,      // Vertically center background
    horizontal_center       :   1,      // Horizontally center background
    fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
    fit_portrait          :   1,      // Portrait images will not exceed browser height
    fit_landscape     :   0,      // Landscape images will not exceed browser width
               
    // Components             
    slide_links       : 'blank',  // Individual links for each slide (Options: false, 'num', 'name', 'blank')
    thumb_links       : 1,      // Individual thumb links for each slide
    thumbnail_navigation    :   0,      // Thumbnail navigation
    slides          :   [     // Slideshow Images
          {image : "#{asset_path('1-kerastase.jpg')}"},
          ],
          
    // Theme Options         
    progress_bar      : 1,      // Timer for each slide             
    mouse_scrub       : 0
    });
  });

app/views/events/edit.html.haml
= render 'form'

app/views/events/index.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    News &amp; Events
  %p.color-white.intro.shadow Services
.table_wrapper
  - @events.each do |event|
    %h3= event.title
    %p
      = image_tag event.image
    = markdown(event.description)
:javascript
  $( document ).ready(function() {
      $.supersized({
    // Functionality
    slideshow               :   0,      // Slideshow on/off
    autoplay        : 1,      // Slideshow starts playing automatically
    start_slide             :   1,      // Start slide (0 is random)
    stop_loop       : 0,      // Pauses slideshow on last slide
    random          :   0,      // Randomize slide order (Ignores start slide)
    slide_interval          :   5000,   // Length between transitions
    transition              :   1,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
    transition_speed    : 2000,   // Speed of transition
    new_window        : 1,      // Image links open in new window/tab
    pause_hover             :   0,      // Pause slideshow on hover
    keyboard_nav            :   0,      // Keyboard navigation on/off
    performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
    image_protect     : 1,      // Disables image dragging and right click with Javascript

    // Size & Position
    min_width           :   0,      // Min width allowed (in pixels)
    min_height            :   0,      // Min height allowed (in pixels)
    vertical_center         :   1,      // Vertically center background
    horizontal_center       :   1,      // Horizontally center background
    fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
    fit_portrait          :   1,      // Portrait images will not exceed browser height
    fit_landscape     :   0,      // Landscape images will not exceed browser width

    // Components
    slide_links       : 'blank',  // Individual links for each slide (Options: false, 'num', 'name', 'blank')
    thumb_links       : 1,      // Individual thumb links for each slide
    thumbnail_navigation    :   0,      // Thumbnail navigation
    slides          :   [     // Slideshow Images
          {image : "#{asset_path('4-kerastase.jpg')}"},
          ],

    // Theme Options
    progress_bar      : 1,      // Timer for each slide
    mouse_scrub       : 0
    });
  });

app/views/home/_email_form.html.haml
.table_wrapper
  - if params[:action] == "specialoffers"
    %p
      We will offer special incentives and promotions through our Website for services and products purchased in our Salon. Some of the specials will be posted on the Website and some will be by “invitation only,” but to get any of these offers you need to be signed up and registered through our online form. Just fill in the few lines in the form, click “Continue” and you’re all set.
  = form_for @message, :url => contact_path do |f|
    %p
      = f.label :name, "Full Name:"
      %br/
      = f.text_field :name
    %p
      = f.label :email,"Email:"
      %br/
      = f.text_field :email
    %p
      = f.label :phone,"Phone:"
      %br/
      = f.text_field :phone
    %p
      = f.label :message,"Message:"
      %br/
      = f.text_area :message, cols:70, rows: 8
    %p
      = f.submit "Submit", :disable_with => 'Submiting...'

app/views/home/contactus.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    Contact us
  %p.color-white.intro.shadow
    Send us your questions or comments
.table_wrapper
  %h1 Contact Us
  = form_for Message.new do |f|
    = f.label :user, "Your name"
:javascript
  $( document ).ready(function() {
      $.supersized({  
    // Functionality
    slideshow               :   0,      // Slideshow on/off
    autoplay        : 1,      // Slideshow starts playing automatically
    start_slide             :   1,      // Start slide (0 is random)
    stop_loop       : 0,      // Pauses slideshow on last slide
    random          :   0,      // Randomize slide order (Ignores start slide)
    slide_interval          :   5000,   // Length between transitions
    transition              :   1,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
    transition_speed    : 2000,   // Speed of transition
    new_window        : 1,      // Image links open in new window/tab
    pause_hover             :   0,      // Pause slideshow on hover
    keyboard_nav            :   0,      // Keyboard navigation on/off
    performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
    image_protect     : 1,      // Disables image dragging and right click with Javascript
               
    // Size & Position               
    min_width           :   0,      // Min width allowed (in pixels)
    min_height            :   0,      // Min height allowed (in pixels)
    vertical_center         :   1,      // Vertically center background
    horizontal_center       :   1,      // Horizontally center background
    fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
    fit_portrait          :   1,      // Portrait images will not exceed browser height
    fit_landscape     :   0,      // Landscape images will not exceed browser width
               
    // Components             
    slide_links       : 'blank',  // Individual links for each slide (Options: false, 'num', 'name', 'blank')
    thumb_links       : 1,      // Individual thumb links for each slide
    thumbnail_navigation    :   0,      // Thumbnail navigation
    slides          :   [     // Slideshow Images
          {image : "#{asset_path('1-kerastase.jpg')}"},
          ],
          
    // Theme Options         
    progress_bar      : 1,      // Timer for each slide             
    mouse_scrub       : 0
    });
  });

app/views/home/events.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    News &amp; Events
  %p.color-white.intro.shadow Services
.table_wrapper
  %h1 Coming Soon...
:javascript
  $( document ).ready(function() {
      $.supersized({  
    // Functionality
    slideshow               :   0,      // Slideshow on/off
    autoplay        : 1,      // Slideshow starts playing automatically
    start_slide             :   1,      // Start slide (0 is random)
    stop_loop       : 0,      // Pauses slideshow on last slide
    random          :   0,      // Randomize slide order (Ignores start slide)
    slide_interval          :   5000,   // Length between transitions
    transition              :   1,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
    transition_speed    : 2000,   // Speed of transition
    new_window        : 1,      // Image links open in new window/tab
    pause_hover             :   0,      // Pause slideshow on hover
    keyboard_nav            :   0,      // Keyboard navigation on/off
    performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
    image_protect     : 1,      // Disables image dragging and right click with Javascript
               
    // Size & Position               
    min_width           :   0,      // Min width allowed (in pixels)
    min_height            :   0,      // Min height allowed (in pixels)
    vertical_center         :   1,      // Vertically center background
    horizontal_center       :   1,      // Horizontally center background
    fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
    fit_portrait          :   1,      // Portrait images will not exceed browser height
    fit_landscape     :   0,      // Landscape images will not exceed browser width
               
    // Components             
    slide_links       : 'blank',  // Individual links for each slide (Options: false, 'num', 'name', 'blank')
    thumb_links       : 1,      // Individual thumb links for each slide
    thumbnail_navigation    :   0,      // Thumbnail navigation
    slides          :   [     // Slideshow Images
          {image : "#{asset_path('4-kerastase.jpg')}"},
          ],
          
    // Theme Options         
    progress_bar      : 1,      // Timer for each slide             
    mouse_scrub       : 0
    });
  });

app/views/home/gallery.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    Gallery
  %p.color-white.intro.shadow About us
.table_wrapper_gallery.padding-photos
  %ul#pikame
    %li
      = image_tag("7.jpg")
    %li
      = image_tag("6.jpg")
    %li
      = image_tag("4.jpg")
    %li
      = image_tag("3.jpg")
:javascript
  $( document ).ready(function() {
      $.supersized({  
    // Functionality
    slideshow               :   0,      // Slideshow on/off
    autoplay        : 1,      // Slideshow starts playing automatically
    start_slide             :   1,      // Start slide (0 is random)
    stop_loop       : 0,      // Pauses slideshow on last slide
    random          :   0,      // Randomize slide order (Ignores start slide)
    slide_interval          :   5000,   // Length between transitions
    transition              :   1,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
    transition_speed    : 2000,   // Speed of transition
    new_window        : 1,      // Image links open in new window/tab
    pause_hover             :   0,      // Pause slideshow on hover
    keyboard_nav            :   0,      // Keyboard navigation on/off
    performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
    image_protect     : 1,      // Disables image dragging and right click with Javascript
               
    // Size & Position               
    min_width           :   0,      // Min width allowed (in pixels)
    min_height            :   0,      // Min height allowed (in pixels)
    vertical_center         :   1,      // Vertically center background
    horizontal_center       :   1,      // Horizontally center background
    fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
    fit_portrait          :   1,      // Portrait images will not exceed browser height
    fit_landscape     :   0,      // Landscape images will not exceed browser width
               
    // Components             
    slide_links       : 'blank',  // Individual links for each slide (Options: false, 'num', 'name', 'blank')
    thumb_links       : 1,      // Individual thumb links for each slide
    thumbnail_navigation    :   0,      // Thumbnail navigation
    slides          :   [     // Slideshow Images
          {image : "#{asset_path('gallery.jpg')}"},
          ],
          
    // Theme Options         
    progress_bar      : 1,      // Timer for each slide             
    mouse_scrub       : 0
    });
  });

app/views/home/haircolor.html.haml
.main-page-text
  %h2.intro.shadow.color-white
    Hair Color
  %p.color-white.intro.shadow Services
.table_wrapper
  %h2 Hair Color
  %table.price-table
    %tbody
      %th
      %th Stylist*
      %th Advanced Stylist*
      %th Senior Stylist*
      %th Master Stylist*
      %tr.odd
        %td Single Process Color
        %td.td-price $45
        %td.td-price $50
        %td.td-price $55
        %td.td-price $55
      %tr
        %td Inoa Single Process
        %td.td-price $75
        %td.td-price $80
        %td.td-price $85
        %td.td-price $85
      %tr.odd
        %td Glaze
        %td.td-price $35
        %td.td-price $35
        %td.td-price $35
        %td.td-price $35
      %tr
        %td Color Balance (Short)
        %td.td-price $65
        %td.td-price $70
        %td.td-price $75
        %td.td-price $75
      %tr.odd
        %td Color Balance (Medium)
        %td.td-price $75
        %td.td-price $80
        %td.td-price $85
        %td.td-price $85
      %tr
        %td Color Balance (Long)
        %td.td-price $85
        %td.td-price $90
        %td.td-price $95
        %td.td-price $95
      %tr.odd
        %td Color Balance (XLong)
        %td.td-price $105
        %td.td-price $110
        %td.td-price $115
        %td.td-price $115
      %tr
        %td Face Frame Highlights
        %td.td-price $85
        %td.td-price $95
        %td.td-price $105
        %td.td-price $105
      %tr.odd
        %td Partial Highlights
        %td.td-price $110
        %td.td-price $120
        %td.td-price $135
        %td.td-price $135
      %td Half-Head Highlights
      %td.td-price $130
      %td.td-price $140
      %td.td-price $160
      %td.td-price $160
      %tr.odd
        %td Full Head Highlights
        %td.td-price $160
        %td.td-price $170
        %td.td-price $190
        %td.td-price $190
      %tr
        %td Baliage
        %td.td-price $140
        %td.td-price $150
        %td.td-price $160
        %td.td-price $160
      %tr.odd
        %td Corrective Color
        %td.td-price{:colspan => "4"} Price upon consultation
      %tr
        %td{:colspan => "5"} * Extra charge for longer length/product use
:javascript
  $( document ).ready(function() {
      $.supersized({  
    // Functionality
    slideshow               :   0,      // Slideshow on/off
    autoplay        : 1,      // Slideshow starts playing automatically
    start_slide             :   1,      // Start slide (0 is random)
    stop_loop       : 0,      // Pauses slideshow on last slide
    random          :   0,      // Randomize slide order (Ignores start slide)
    slide_interval          :   5000,   // Length between transitions
    transition              :   1,      // 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
    transition_speed    : 2000,   // Speed of transition
    new_window        : 1,      // Image links open in new window/tab
    pause_hover             :   0,      // Pause slideshow on hover
    keyboard_nav            :   0,      // Keyboard navigation on/off
    performance       : 1,      // 0-Normal, 1-Hybrid speed/quality, 2-Optimizes image quality, 3-Optimizes transition speed // (Only works for Firefox/IE, not Webkit)
    image_protect     : 1,      // Disables image dragging and right click with Javascript
               
    // Size & Position               
    min_width           :   0,      // Min width allowed (in pixels)
    min_height            :   0,      // Min height allowed (in pixels)
    vertical_center         :   1,      // Vertically center background
    horizontal_center       :   1,      // Horizontally center background
    fit_always        : 0,      // Image will never exceed browser width or height (Ignores min. dimensions)
    fit_portrait          :   1,      // Portrait images will not exceed browser height
    fit_landscape     :   0,      // Landscape images will not exceed browser width
               
    // Components             
    slide_links       : 'blank',  // Individual links for each slide (Options: false, 'num', 'name', 'blank')
    thumb_links       : 1,      // Individual thumb links for each slide
    thumbnail_navigation    :   0,      // Thumbnail navigation
    slides          :   [     // Slideshow Images
          {image : "#{asset_path('hair-color.jpg')}"},
          ],
          
    // Theme Options         
    progress_bar      : 1,      // Timer for each slide             
    mouse_scrub       : 0
    });
  });

app/views/layouts/_nav.html.haml
%nav#cssmenu
  %ul
    %li.active.has-sub
      = link_to "Services"
      %ul
        %li
          = link_to "Haircut & Styling", haircut_path
        %li
          = link_to "Hair Color", haircolor_path
        %li
          = link_to "Hair Treatments", hairtreatment_path
        %li
          = link_to "Hair Rituals", hairrituals_path
    %li.active.has-sub
      = link_to "About us"
      %ul
        %li
          = link_to "Gallery", gallery_path
        %li
          = link_to "Products", products_path
    %li= link_to "Our Team", teams_path
    %li= link_to "News & Events", events_path
    %li= link_to "Special Offers", specialoffers_path
    %li= link_to "Contact us", contact_path
%ul.location.color-white.hours_wrapper
  %li.bold.address_padding.hours_size Address
  %li
    10300 W Forest Hill Blvd #2000
    %br/
    Wellington, FL 33414
  %li.bold.address_padding
    Phone
  %li 561-753-0052

app/views/layouts/admin/administrations.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tricho
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    = javascript_include_tag 'application'
  %body.admin-area
    - if flash[:notice]
      .flash-notice
        = flash[:notice]
    .nav-menu
      .logo-area.float-left
        = link_to(image_tag("tricho-salon-wellington.png"), root_path)
      .nav-area.float-right
        %ul
          %li
            = link_to "Team Members", admin_teams_path
          %li
            = link_to "Add Team Member", new_admin_team_path
          %li
            = link_to "Events", admin_events_path
          %li
            = link_to "Add Event", new_admin_event_path
          %li
            = link_to "Log Out", destroy_user_session_path, method: "DELETE"
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tricho
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    = javascript_include_tag 'application'
  %body
    - if flash[:notice]
      .flash-notice
        = flash[:notice]
    .logo-area
      = link_to(image_tag("tricho-salon-wellington.png"), root_path)
    = render "layouts/nav"
    = yield